name: mojadwel_web
description: "The web page and dashboard of mojadwel"
publish_to: "none"
# --------------------------------------------------------------------------------
# THE_APP_VERSION
version: 0.0.1
# --------------------------------------------------------------------------------
environment:
  sdk: ">=3.8.1 <4.0.0"
# --------------------------------------------------------------------------------
dependencies:
  clipboard: ^2.0.2
  flutter:
    sdk: flutter
  # ------------------------------------
  # NO NEED - FOR REFERENCE
#    flutter_launcher_icons: ^0.14.4
#  launcher_name: ^1.0.2
  # ------------------------------------
  go_router: ^15.1.2
  image: ^4.5.4
  http: ^1.5.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  collection: ^1.19.1
  cloud_firestore: ^6.0.0
  firebase_database: ^12.0.0
  firebase_storage: ^13.0.0
  # ------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  # ------------------------------------
  #flutter_launcher_icons:
  #  android: true
  #  ios: true
  #  image_path: "assets/logo_plain.jpg"
  #  adaptive_icon_background: "#5943e9"
  #  adaptive_icon_foreground: "assets/logo_plain.jpg"
  #  adaptive_icon_foreground_inset: 0
  #  windows:
  #    generate: true
  #    image_path: "assets/logo_plain.jpg"
  #    icon_size: 48 # min:48, max:256, default: 48
  # ------------------------------------
#launcher_name:
#  default: "Mojadwel"
# --------------------------------------------------------------------------------
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png
    - assets/logo.svg
#    - assets/banner.jpg
#    - assets/icon_white.png
#    - assets/logo.jpg
#    - assets/name.png
  # --------------------------------------------------------------------------------
  fonts:
    - family: headline
      fonts:
        - asset: assets/fonts/headline.ttf
    - family: body
      fonts:
        - asset: assets/fonts/body.ttf
# --------------------------------------------------------------------------------